"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from rose.model import HeliotropeGalleryInfo, HeliotropeImages, HeliotropeInfo, HeliotropeIntegrated, HeliotropeList

class Client:
    def __init__(self, authorization: str) -> None:
        ...
    
    async def request(self, method: str, path: str, json: Optional[dict[str, Any]] = ...) -> Any:
        ...
    
    async def galleryinfo(self, index: int) -> HeliotropeGalleryInfo:
        ...
    
    async def info(self, index: int) -> HeliotropeInfo:
        ...
    
    async def integrated(self, index: int) -> HeliotropeIntegrated:
        ...
    
    async def list_(self, number: int) -> HeliotropeList:
        ...
    
    async def index(self) -> list[int]:
        ...
    
    async def images(self, index: int) -> HeliotropeImages:
        ...
    


