"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterator

class HeliotropeFile:
    def __init__(self, **file: Any) -> None:
        ...
    
    @classmethod
    def parsing(cls, value_datas: dict[str, list[dict[str, str]]], key: str) -> Iterator[HeliotropeFile]:
        ...
    


class HeliotropeValueData:
    def __init__(self, **tag: Any) -> None:
        ...
    
    @classmethod
    def parsing(cls, value_datas: dict[str, list[dict[str, str]]], key: str) -> Iterator[HeliotropeValueData]:
        ...
    


class HeliotropeImage:
    def __init__(self, **data: Any) -> None:
        ...
    
    @classmethod
    def parsing(cls, value_datas: dict[str, list[dict[str, str]]], key: str) -> Iterator[HeliotropeImage]:
        ...
    


class HeliotropeGalleryInfo:
    def __init__(self, **data: Any) -> None:
        ...
    


class HeliotropeInfo:
    def __init__(self, **data: Any) -> None:
        ...
    


class HeliotropeIntegrated:
    def __init__(self, **data: Any) -> None:
        ...
    


class HeliotropeList:
    def __init__(self, **data: Any) -> None:
        ...
    


class HeliotropeImages:
    def __init__(self, **data: Any) -> None:
        ...
    


